default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: root
      password: password
      database: postgres
      schema: public
      port: 5432
