FROM python:3.9.16

WORKDIR /app

RUN apt-get update -y && \
    apt-get install -y \
    g++ \
    unixodbc-dev \
    libsasl2-modules-gssapi-mit \
    unzip

RUN pip install --upgrade pip \
    && pip install dbt-databricks~=1.4.0 \
    && pip install memory_profiler

RUN mkdir -p /root/.dbt
COPY dbt/profiles.yml /root/.dbt/profiles.yml

ENV DBT_TARGET_NAME=databricks
